--USE SUBASHAGENCIES

CREATE PROCEDURE ADD_BEAT  (@BEAT_NAME VARCHAR(200),
							@OUTLET_COUNT INT)
AS
BEGIN
	DECLARE @COUNT AS INT;
	DECLARE @BEATID AS VARCHAR(10);

	SELECT @COUNT = COUNT(*) FROM BEAT_MASTER

	SET @BEATID = 'B' + CONVERT(VARCHAR(10), @COUNT)

	INSERT INTO BEAT_MASTER (BEAT_ID, 
							BEAT_NAME, 
							OUTLET_COUNT)
					VALUES (@BEATID,
							@BEAT_NAME,
							@OUTLET_COUNT);

END

