--USE SUBASHAGENCIES

ALTER PROCEDURE ADD_EMPLOYEE   (@FIRST_NAME VARCHAR(50),
								@LAST_NAME VARCHAR(50),
								@JOINING_DATE DATE,
								@DESIGNATION_ID VARCHAR(10),
								@SALARY INT,
								@STATUS_ID VARCHAR(10))
								--,@RECORD_INSERTED INT OUTPUT)
AS
BEGIN
	DECLARE @COUNT INT,
			@EMPLOYEE_ID AS VARCHAR(10);

	SELECT @COUNT = COUNT(*) FROM EMPLOYEE_MASTER;

	SET @EMPLOYEE_ID = 'E' + CONVERT(VARCHAR(10), @COUNT);

	INSERT INTO EMPLOYEE_MASTER(EMPLOYEE_ID, 
								FIRST_NAME, 
								LAST_NAME, 
								JOINING_DATE, 
								DESIGNATION_ID, 
								SALARY, 
								STATUS_ID) 
				VALUES( @EMPLOYEE_ID, 
						@FIRST_NAME, 
						@LAST_NAME, 
						@JOINING_DATE, 
						@DESIGNATION_ID, 
						@SALARY, 
						@STATUS_ID)
	

	--SELECT @RECORD_INSERTED = @@ROWCOUNT;

END