USE SUBASHAGENCIES

CREATE TABLE DESIGNATION_MASTER (DESIGNATION_ID VARCHAR(10) PRIMARY KEY, DESIGNATION_NAME VARCHAR(100) NOT NULL)

INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D0','---SELECT---');
INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D1','SALESMAN');
INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D2','COLLECTION EXEC');
INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D3','SALES & COLLECTION');
INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D4','AUTO DRIVER');
INSERT INTO DESIGNATION_MASTER(DESIGNATION_ID, DESIGNATION_NAME) VALUES ('D5','SALES & DRIVER');