USE SUBASHAGENCIES

CREATE TABLE STATUS_MASTER (STATUS_ID VARCHAR(10) PRIMARY KEY,
							STATUS_TEXT VARCHAR(50) NOT NULL)


INSERT INTO STATUS_MASTER (STATUS_ID, STATUS_TEXT) VALUES ('S0','---SELECT---')
INSERT INTO STATUS_MASTER (STATUS_ID, STATUS_TEXT) VALUES ('S1','ACTIVE')
INSERT INTO STATUS_MASTER (STATUS_ID, STATUS_TEXT) VALUES ('S2','INACTIVE')